// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/editor-vibes/AiryGhost.tsx": () => import("../components/mockups/editor-vibes/AiryGhost.tsx"),
  "./components/mockups/editor-vibes/DarkFocused.tsx": () => import("../components/mockups/editor-vibes/DarkFocused.tsx"),
  "./components/mockups/editor-vibes/WarmLiterary.tsx": () => import("../components/mockups/editor-vibes/WarmLiterary.tsx")
};
